// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxwfq1Tl10Hwtd4TuWOzSDTKOtxBdAqes',
    appId: '1:765521707078:web:1e15716165094a5ec1ca47',
    messagingSenderId: '765521707078',
    projectId: 'boipara-eb181',
    authDomain: 'boipara-eb181.firebaseapp.com',
    storageBucket: 'boipara-eb181.firebasestorage.app',
    measurementId: 'G-RNN5FWR8LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP12UhaEiR27stIsYpeHcXTTmf_A61xDU',
    appId: '1:765521707078:android:26c64d04da94f3adc1ca47',
    messagingSenderId: '765521707078',
    projectId: 'boipara-eb181',
    storageBucket: 'boipara-eb181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZmBuK3YbV6eDVCUbMd6-PR59W468YQaE',
    appId: '1:765521707078:ios:f09994770e357fd5c1ca47',
    messagingSenderId: '765521707078',
    projectId: 'boipara-eb181',
    storageBucket: 'boipara-eb181.firebasestorage.app',
    iosBundleId: 'com.example.boipara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZmBuK3YbV6eDVCUbMd6-PR59W468YQaE',
    appId: '1:765521707078:ios:f09994770e357fd5c1ca47',
    messagingSenderId: '765521707078',
    projectId: 'boipara-eb181',
    storageBucket: 'boipara-eb181.firebasestorage.app',
    iosBundleId: 'com.example.boipara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxwfq1Tl10Hwtd4TuWOzSDTKOtxBdAqes',
    appId: '1:765521707078:web:7e8007cf4cb3d002c1ca47',
    messagingSenderId: '765521707078',
    projectId: 'boipara-eb181',
    authDomain: 'boipara-eb181.firebaseapp.com',
    storageBucket: 'boipara-eb181.firebasestorage.app',
    measurementId: 'G-X9823353E3',
  );
}
